on:
    push:
        branches:
            - main
    pull_request:

name: CI

jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer

        runs-on: ubuntu-latest

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2

            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga:2.16.7
              with:
                  args: --diff --dry-run

    composer-normalize:
        name: composer-normalize

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: composer-normalize
              uses: docker://ergebnis/composer-normalize-action:0.8.0

    phpstan:
        name: PHPStan

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: PHPStan
              uses: docker://oskarstark/phpstan-ga:0.12.49
              with:
                  args: analyse src --level=7

    test:
        name: PHP ${{ matrix.php-version }}

        runs-on: ubuntu-latest

        continue-on-error: ${{ matrix.allowed_to_fail }}

        strategy:
            matrix:
                php-version:
                    - '7.2'
                    - '7.3'
                    - '7.4'
                allowed_to_fail: [false]

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install PHP with extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  tools: composer:v2

            - name: Add PHPUnit matcher
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Set Composer cache directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Cache Composer
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ matrix.variant }}
                  restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-

            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-progress --no-interaction

            - name: Run Tests
              run: make test
