on:
    push:
        branches:
            - main
    pull_request:

name: CI

jobs:
    php-cs-fixer:
        name: PHP-CS-Fixer

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: PHP-CS-Fixer
              uses: docker://oskarstark/php-cs-fixer-ga:2.16.4
              with:
                  args: --diff --dry-run

    composer-normalize:
        name: composer-normalize

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: composer-normalize
              uses: docker://ergebnis/composer-normalize-action:0.8.0

    phpstan:
        name: PHPStan

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: PHPStan
              uses: docker://oskarstark/phpstan-ga:0.12.48
              with:
                  args: analyse src --level=7
